version: "3.3" # optional since v1.27.0
services:
  api:
    image: alpine
    build: .
    ports:
      - "3080:3080"
    volumes:
      - .:/opt/
    entrypoint: [ "sh", "/opt/entrypoint.sh" ]
volumes:
  MCB: {}
